services:
  backend:
    container_name: backend_cw
    image: lunghr/domoy:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: database_cw
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: adminer_cw
    restart: always
    ports:
      - "13228:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database_cw
