package com.example.domoycoursework.models.enums

enum class ApplicationTheme {
    WATER_SUPPLY,
    ELECTRICITY,
    HEATING,
    SEWERAGE,
    GAS_SUPPLY,
    INTERNET_TV,
    ELEVATOR,
    ROOF_LEAK,
    COMMON_AREA_CLEANING,
    YARD_LANDSCAPING,
    TRASH_DISPOSAL,
    PARKING_ISSUES,
    SECURITY,
    NOISE_COMPLAINT,
    PET_ISSUES,
    ILLEGAL_CONSTRUCTION,
    DOCUMENT_REQUEST,
    RENTAL_QUESTIONS,
    OTHER
}